language: ruby
rvm:
  - 2.3.2
  - 2.4.1
  - 2.5.0
  - 2.6.0
  - 2.7.0
before_install: gem install bundler -v 2.1.2
addons:
  code_climate:
    repo_token: 1afbd216b9257514ff1afcaa7b8a121bc83e5238b4c3c6f4dad80107c4ea487d
